services:
  postgres:
    image: postgres
    container_name: container-pg
    restart: always
    hostname: localhost
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: guest
      POSTGRES_PASSWORD: guest
      POSTGRES_DB: job_processor
    volumes:
      - postgres_data_job_processor:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:4-management
    container_name: container-rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  postgres_data_job_processor: